### ISSUE TITLE
Updated install command, replace libtool with libtool-bin

### ISSUE THREAD

**Issue by niekvanderven** [martenjacobs/ToonRooter#1]
Hi Marten,
Great tool during install i had to change the libtool package to libtool-bin.
I used it on the following fresh image and did first update/upgared + reboot: 2018-03-13-raspbian-stretch.img
So if its not only me  can you update the instlall notes ?

sudo apt-get install libtool-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  autotools-dev libltdl-dev libtool
Suggested packages:
  libtool-doc autoconf automaken gfortran | fortran95-compiler gcj-jdk
The following NEW packages will be installed:
  autotools-dev libltdl-dev libtool libtool-bin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,207 kB of archives.
After this operation, 3,071 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.nl.leaseweb.net/raspbian/raspbian stretch/main armhf autotools-dev all 20161112.1 [73.4 kB]
Get:2 http://mirror.nl.leaseweb.net/raspbian/raspbian stretch/main armhf libltdl-dev armhf 2.4.6-2 [159 kB]
Get:3 http://mirror.nl.leaseweb.net/raspbian/raspbian stretch/main armhf libtool all 2.4.6-2 [545 kB]
Get:4 http://mirror.nl.leaseweb.net/raspbian/raspbian stretch/main armhf libtool-bin armhf 2.4.6-2 [430 kB]
Fetched 1,207 kB in 0s (1,810 kB/s)  
Selecting previously unselected package autotools-dev.
(Reading database ... 124697 files and directories currently installed.)
Preparing to unpack .../autotools-dev_20161112.1_all.deb ...
Unpacking autotools-dev (20161112.1) ...
Selecting previously unselected package libltdl-dev:armhf.
Preparing to unpack .../libltdl-dev_2.4.6-2_armhf.deb ...
Unpacking libltdl-dev:armhf (2.4.6-2) ...
Selecting previously unselected package libtool.
Preparing to unpack .../libtool_2.4.6-2_all.deb ...
Unpacking libtool (2.4.6-2) ...
Selecting previously unselected package libtool-bin.
Preparing to unpack .../libtool-bin_2.4.6-2_armhf.deb ...
Unpacking libtool-bin (2.4.6-2) ...
Setting up libltdl-dev:armhf (2.4.6-2) ...
Setting up autotools-dev (20161112.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libtool (2.4.6-2) ...
Setting up libtool-bin (2.4.6-2) ...
pi@raspberrypi:~/openocd $

**Comment by martenjacobs** [comment]
I don't know if this is necessary, but it can't hurt to install both
