### ISSUE TITLE
Request to log generated password

### ISSUE THREAD

**Issue by pmolenaar** [martenjacobs/ToonRooter#17]
Would it be possible to save the generated root password to a file? I was stupid enough to not write it down (root access only achieved after midnight and after several hours of tinkering) so I basically have to do it all again for my R10 Toon model...

**Comment by martenjacobs** [comment]
Not after the fact. During rooting you could always use `tee` to send the output to a file.

**Comment by martenjacobs** [comment]
By the way, the script outputs a private key pair which you can use to log in.
