### ISSUE TITLE
Rpi4 cfg file

### ISSUE THREAD

**Issue by Bart-1992** [martenjacobs/ToonRooter#18]
Could someone have a look at a raspi4 cfg file? Tried the script using a pi4 but without succes. Would like to root my Toon, but only have a raspi4 :)!

Thanks! 
Br,
Bart

**Comment by martenjacobs** [comment]
I think that would be possible, but I don't have a Toon anymore and I don't have a Pi 4 either. It's probably best to try and find an OpenOCD config somewhere on the internet and use that (the config is not all that specific to this script). If you find one please let me know and I'll add it

**Comment by Bart-1992** [comment]
Hi Marten,

Made one based on the rpi3 cfg file. Everything worked fine for me ;)!

Thanks,
[rpi4.cfg.txt](https://github.com/martenjacobs/ToonRooter/files/3720711/rpi4.cfg.txt)

**Comment by martenjacobs** [comment]
@Bart-1992 Thanks for the file, I've included it
