### ISSUE TITLE
The procedure stalls at INFO:rooter:Logging in to U-Boot

### ISSUE THREAD

**Issue by RienduPre** [martenjacobs/ToonRooter#19]
The procedure stalls at INFO:rooter:Logging in to U-Boot

Tried it many times and doublechecked the wiring.

All help is welcome!

<img width="645" alt="Schermafbeelding 2019-10-20 om 20 47 55" src="https://user-images.githubusercontent.com/9009949/67164466-0f9d3a00-f37b-11e9-8e0d-ebb167bf7e51.png">

**Comment by martenjacobs** [comment]
Please refer questions about usage to [this friendly forum](https://www.domoticaforum.eu/viewtopic.php?f=101&t=11999). There are many people with similar issues there. If you try with `--output-level DEBUG` the output is much more verbose. You'll probably find someone with a very similar issue on that thread, along with the solution.
