### ISSUE TITLE
Ready made package to load ?

### ISSUE THREAD

**Issue by spacecabbie** [martenjacobs/ToonRooter#21]
Would be an idea to create ready made image ?
with for example:
https://github.com/RPi-Distro/pi-gen
I have never done it before but could have a go.

Or are there licensing concerns ?

Also does this only require the jtag wiring? 
Sorry for asking but there are so many guides atm when searching its hard to find a good visual guide on what to connect the unix stuff i can do with 2 vingers in my nose :P

**Comment by martenjacobs** [comment]
> Would be an idea to create ready made image ?
with for example:
> https://github.com/RPi-Distro/pi-gen
> I have never done it before but could have a go.

Knock yourself out, I’m not using a Toon anymore so I’m not really actively supporting this package anymore. If you create an image I’ll be happy to link to it. 

> Or are there licensing concerns ?

No idea. I would’t think an image would have more issues than this repo. If required in any way, I hereby give you permission to embed this script in an image. 

> Also does this only require the jtag wiring?

You need JTAG and serial. Please see the readme to find the correct wiring scheme. There’s also a thread on Domotica Forum dedicated to this script.
