### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by PvdGulik** [martenjacobs/ToonRooter#23]
Hello Marten,

After following this:

```
> Then get and run this application:

> sudo apt install python-serial python-cryptography
> git clone https://github.com/martenjacobs/ToonRooter.git
> cd ToonRooter
> sudo python . --jtag-available

> Then reset your Toon and let the magic happen :)
```

I connected the Toon via Wifi, and did SSH root@ip-address.
Then password is asked. I tried:

```
f4E9J
3BHf2
toon
Toon
```

But none works. In what did you ToonRooter changed the password?

Thank you, Pieter

**Comment by martenjacobs** [comment]
Hi Pieter,

The script sets the root password to a randomly generated value. The script outputs the password during rooting, so if you logged the output somewhere you could use that. I'm not using a default password as no one will ever change it (there's no `passwd` command on the Toon to do so), causing a security issue. 

The best way to log in through SSH is to use the private key file that's generated by the script and output to `id_rsa` in its working directory (usually the same directory as where the script resides). 

If you don't know how to do so, it's basically this: 
- `cd` into the directory where the script is (and check if there's a file called `id_rsa` in there)
- run `ssh -i id_rsa root@[TOON IP]`
- It should now log in without asking for a password

Cheers,
Marten

**Comment by PvdGulik** [comment]
Hello Marten

Thank you, succeeded!

Pieter

Op 19 jan. 2021 om 18:19 heeft Marten Jacobs <notifications@github.com> het volgende geschreven:

﻿

Hi Pieter,

The script sets the root password to a randomly generated value. The script outputs the password during rooting, so if you logged the output somewhere you could use that. I'm not using a default password as no one will ever change it (there's no passwd command on the Toon to do so), causing a security issue.

The best way to log in through SSH is to use the private key file that's generated by the script and output to id_rsa in its working directory (usually the same directory as where the script resides).

If you don't know how to do so, it's basically this:

  *   cd into the directory where the script is (and check if there's a file called id_rsa in there)
  *   run ssh -i id_rsa root@[TOON IP]
  *   It should now log in without asking for a password

Cheers,
Marten
